language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7" # not available yet - 17th July 2018
dist: xenial
sudo: true

install:
  - pip install --upgrade pip setuptools
  - pip install git+git://github.com/project-gemmi/gemmi.git
  - pip install coveralls

# Command to run tests
#script: python setup.py test
script: coverage run --source adding_stats_to_mmcif setup.py test

after_success:
    coveralls