language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
#  - "3.7" # requires the following two lines (17th July 2018)
# dist: xenial # for python 3.7
# sudo: true # for python 3.7

install:
  - pip install --upgrade pip setuptools
  - pip install git+git://github.com/project-gemmi/gemmi.git
  - pip install coveralls

# Command to run tests
#script: python setup.py test
script: coverage run --source adding_stats_to_mmcif setup.py test

after_success:
    coveralls