import os


class TestFiles:

    def __init__(self):
        self.FILE_ROOT = os.path.dirname(os.path.realpath(__file__))
        self.path = os.path.dirname(os.path.join(self.FILE_ROOT, '..', '..'))
        self.test_data = os.path.join(self.path, 'test_data')
        self.TEST_AIMLESS_XML_FILE = os.path.join(self.test_data, "aimless_example.xml")
        self.TEST_AIMLESS_XML_FILE_NO_DATA = os.path.join(self.test_data, "aimless_example_no_data.xml")
        self.TEST_BAD_XML_FILE = os.path.join(self.test_data, "bad_example.xml")
        self.TEST_NON_AIMLESS_XML_FILE = os.path.join(self.test_data, "non_aimless_example.xml")
        self.TEST_INVALID_MMCIF_FILE = os.path.join(self.test_data, "invalid.cif")
        self.TEST_VALID_MMCIF_FILE = os.path.join(self.test_data, "valid.cif")
        self.TEST_INVALID_FASTA_ONE_SEQUENCE = os.path.join(self.test_data, "invalid.fasta")

        self.fasta = None
        self.cif = None
        self.sample_seq = None
        self.observed_seq = None

    def one_sequence(self):
        self.fasta = os.path.join(self.test_data, "one_chain.fasta")
        self.cif = os.path.join(self.test_data, "valid.cif")
        self.sample_seq = {
            'pdb|3zt9|A': 'MEKLEVGIYTRAREGEIACGDACLVKRVEGVIFLAVGDGIGHGPEAARAAEIAIASMESSMNTGLVNIFQLCHRELRGTRGAVAALCRVDRRQGLWQAAIVGNIHVKILSAKGIITPLATPGILGYNYPHQLLIAKGSYQEGDLFLIHSDGIQEGAVPLALLANYRLTAEELVRLIGEKYGRRDDDVAVIVAR'}
        self.observed_seq = dict()
        self.observed_seq['1'] = {
            'sequence': 'EKLEVGIYTRAREGEIACGDACLVKRVEGVIFLAVGDGIGHGPEAARAAEIAIASMESSMNTGLVNIFQLCHRELRGTRGAVAALCRVDRRQGLWQAAIVGNIHVKILSAKGIITPLATPGILGYNYPHQLLIAKGSYQEGDLFLIHSDGIQEGAVPLALLANYRLTAEELVRLIGEKYGRRDDDVAVIVAR',
            'chains': ['A']}

    def four_chains_one_polymer(self):
        self.fasta = os.path.join(self.test_data, "four_chains_one_polymer.fasta")
        self.cif = os.path.join(self.test_data, "pdb6fqf_refmac1.cif")
        self.sample_seq = {
            'pdb|6fqf|A B C D': 'VHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH'}
        self.observed_seq = dict()
        self.observed_seq['1'] = {
            'sequence': 'VHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH',
            'chains': ['AAA', 'BBB', 'CCC', 'DDD']}

    def three_sequences(self):
        self.fasta = os.path.join(self.test_data, "three_chains.fasta")
        self.sample_seq = {'pdb|6db6|P': 'YNKRKRIHIGPGRAFYTTKNIIG',
                           'pdb|6db6|H': 'QVQLVQSGAEVKKPGASVKISCKASGYNFTTYAMHWVRQAPGQGLEWMGWINGGNGDTRYSQKFRGRVTISRDTSASTAYMELHSLTSEDTALFYCARESGDYYSEISGALDWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKRVEPKSCDKTH',
                           'pdb|6db6|L': 'SYELTQPPSVSVSPGQTARITCSGDVLPKKYAYWYQQKSGLAPVLVIYEDNRRPSGIPERFSGSSSGTMATLTISGAQVEDEGDYYCSSTDSSGDHYVFGTGTKVTVLGQPKANPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS'}

    def five_sequences(self):
        self.fasta = os.path.join(self.test_data, "five_chains.fasta")
        self.cif = os.path.join(self.test_data, "5l1z_refmac1.cif")
        self.sample_seq = {
            'pdb|5l1z|B': 'MEGERKNNNKRWYFTREQLENSPSRRFGVDPDKELSYRQQAANLLQDMGQRLNVSQLTINTAIVYMHRFYMIQSFTQFPGNSVAPAALFLAAKVEEQPKKLEHVIKVAHTCLHPQESLPDTRSEAYLQQVQDLVILESIILQTLGFELTIDHPHTHVVKCTQLVRASKDLAQTSYFMATNSLHLTTFSLQYTPPVVACVCIHLACKWSNWEIPVSTDGKHWWEYVDATVTLELLDELTHEFLQILEKTPNRLKRIWNWRACEAA',
            'pdb|5l1z|D': 'XMEPVDPRLEPWKHPGSQPKTACTNCYCKKCCFHCQVCFITKALGISYGRKKRRQRRR',
            'pdb|5l1z|C': 'SPLFAEPYKVTSKEDKLSSRIQSMLGNYDEMKDFIG',
            'pdb|5l1z|A': 'MAKQYDSVECPFCDEVSKYEKLAKIGQGTFGEVFKARHRKTGQKVALKKVLMENEKEGFPITALREIKILQLLKHENVVNLIEICRTKASPYNRCKGSIYLVFDFCEHDLAGLLSNVLVKFTLSEIKRVMQMLLNGLYYIHRNKILHRDMKAANVLITRDGVLKLADFGLARAFSLAKNSQPNRYTNRVVTLWYRPPELLLGERDYGPPIDLWGAGCIMAEMWTRSPIMQGNTEQHQLALISQLCGSITPEVWPNVDNYELYEKLELVKGQKRKVKDRLKAYVRDPYALDLIDKLLVLDPAQRIDSDDALNHDFFWSDPMPSDLKGMLST',
            'pdb|5l1z|N': 'AGAUCUGAGCCUGGGAGCUCUCU'}
        self.observed_seq = dict()
        self.observed_seq['2'] = {
            'sequence': 'NNNKRWYFTREQLENSPSRRFGVDPDKELSYRQQAANLLQDMGQRLNVSQLTINTAIVYMHRFYMIQSFTQFPGNSVAPAALFLAAKVEEQPKKLEHVIKVAHTCLHPQESLPDTRSEAYLQQVQDLVILESIILQTLGFELTIDHPHTHVVKCTQLVRASKDLAQTSYFMATNSLHLTTFSLQYTPPVVACVCIHLACKWSNWEIPVSTDGKHWWEYVDATVTLELLDELTHEFLQILEKTPNRLKRIWNWRAC',
            'chains': ['BBB']}
        self.observed_seq['5'] = {'sequence': 'MEPVDPRLEPWKHPGSQPKTACTNCYCKKCCFHCQVCFITKALGISYGR',
                                  'chains': ['DaD']}
        self.observed_seq['3'] = {'sequence': 'LFAEPYKVTSKEDKLSSRIQSMLGNYDEMKDFIG',
                                  'chains': ['CCC']}
        self.observed_seq['1'] = {
            'sequence': 'VECPFCDEVSKYEKLAKIGGEVFKARHRKTGQKVALKKVLMENEKEGFPITALREIKILQLLKHENVVNLIEICRTKGSIYLVFDFCEHDLAGLLSNVLVKFTLSEIKRVMQMLLNGLYYIHRNKILHRDMKAANVLITRDGVLKLADFGLARAFSLAKNSQPNRYTNRVVTLWYRPPELLLGERDYGPPIDLWGAGCIMAEMWTRSPIMQGNTEQHQLALISQLCGSITPEVWPNVDNYELYEKLELVKGQKRKVKDRLKAYVRDPYALDLIDKLLVLDPAQRIDSDDALNHDFFWSDPMPSDLKGMLST',
            'chains': ['AAA']}
        self.observed_seq['6'] = {'sequence': 'GAUCUGAGCCUGGGAGCUCUC',
                                  'chains': ['NNN']}
